
package Domain;


/**
 *
 * @author oamongec
 */
public class BoardJFrame extends javax.swing.JFrame {

    /**
     * Creates new form VistaTablero
     */
    public BoardJFrame() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.setTitle("DAMAS GAME");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnA8 = new javax.swing.JButton();
        btnB8 = new javax.swing.JButton();
        btnC8 = new javax.swing.JButton();
        btnD8 = new javax.swing.JButton();
        btnE8 = new javax.swing.JButton();
        btnF8 = new javax.swing.JButton();
        btnG8 = new javax.swing.JButton();
        btnH8 = new javax.swing.JButton();
        btnA7 = new javax.swing.JButton();
        btnB7 = new javax.swing.JButton();
        btnC7 = new javax.swing.JButton();
        btnD7 = new javax.swing.JButton();
        btnE7 = new javax.swing.JButton();
        btnF7 = new javax.swing.JButton();
        btnG7 = new javax.swing.JButton();
        btnH7 = new javax.swing.JButton();
        btnA6 = new javax.swing.JButton();
        btnB6 = new javax.swing.JButton();
        btnC6 = new javax.swing.JButton();
        btnD6 = new javax.swing.JButton();
        btnE6 = new javax.swing.JButton();
        btnF6 = new javax.swing.JButton();
        btnG6 = new javax.swing.JButton();
        btnH6 = new javax.swing.JButton();
        btnA5 = new javax.swing.JButton();
        btnB5 = new javax.swing.JButton();
        btnC5 = new javax.swing.JButton();
        btnD5 = new javax.swing.JButton();
        btnE5 = new javax.swing.JButton();
        btnF5 = new javax.swing.JButton();
        btnG5 = new javax.swing.JButton();
        btnH5 = new javax.swing.JButton();
        btnA4 = new javax.swing.JButton();
        btnB4 = new javax.swing.JButton();
        btnC4 = new javax.swing.JButton();
        btnD4 = new javax.swing.JButton();
        btnE4 = new javax.swing.JButton();
        btnF4 = new javax.swing.JButton();
        btnG4 = new javax.swing.JButton();
        btnH4 = new javax.swing.JButton();
        btnA3 = new javax.swing.JButton();
        btnB3 = new javax.swing.JButton();
        btnC3 = new javax.swing.JButton();
        btnD3 = new javax.swing.JButton();
        btnE3 = new javax.swing.JButton();
        btnF3 = new javax.swing.JButton();
        btnG3 = new javax.swing.JButton();
        btnH3 = new javax.swing.JButton();
        btnA2 = new javax.swing.JButton();
        btnB2 = new javax.swing.JButton();
        btnC2 = new javax.swing.JButton();
        btnD2 = new javax.swing.JButton();
        btnE2 = new javax.swing.JButton();
        btnF2 = new javax.swing.JButton();
        btnG2 = new javax.swing.JButton();
        btnH2 = new javax.swing.JButton();
        btnA1 = new javax.swing.JButton();
        btnB1 = new javax.swing.JButton();
        btnC1 = new javax.swing.JButton();
        btnD1 = new javax.swing.JButton();
        btnE1 = new javax.swing.JButton();
        btnF1 = new javax.swing.JButton();
        btnG1 = new javax.swing.JButton();
        btnH1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new java.awt.GridLayout(8, 8));

        btnA8.setBackground(new java.awt.Color(204, 255, 204));
        btnA8.setToolTipText("");
        btnA8.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.add(btnA8);

        btnB8.setBackground(new java.awt.Color(120, 120, 120));
        btnB8.setToolTipText("");
        btnB8.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.add(btnB8);

        btnC8.setBackground(new java.awt.Color(204, 255, 204));
        btnC8.setToolTipText("");
        btnC8.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.add(btnC8);

        btnD8.setBackground(new java.awt.Color(120, 120, 120));
        btnD8.setToolTipText("");
        btnD8.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.add(btnD8);

        btnE8.setBackground(new java.awt.Color(204, 255, 204));
        btnE8.setToolTipText("");
        btnE8.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.add(btnE8);

        btnF8.setBackground(new java.awt.Color(120, 120, 120));
        btnF8.setToolTipText("");
        btnF8.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.add(btnF8);

        btnG8.setBackground(new java.awt.Color(204, 255, 204));
        btnG8.setToolTipText("");
        btnG8.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.add(btnG8);

        btnH8.setBackground(new java.awt.Color(120, 120, 120));
        btnH8.setToolTipText("");
        btnH8.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.add(btnH8);

        btnA7.setBackground(new java.awt.Color(120, 120, 120));
        btnA7.setToolTipText("");
        btnA7.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.add(btnA7);

        btnB7.setBackground(new java.awt.Color(204, 255, 204));
        btnB7.setToolTipText("");
        btnB7.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.add(btnB7);

        btnC7.setBackground(new java.awt.Color(120, 120, 120));
        btnC7.setToolTipText("");
        btnC7.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.add(btnC7);

        btnD7.setBackground(new java.awt.Color(204, 255, 204));
        btnD7.setToolTipText("");
        btnD7.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.add(btnD7);

        btnE7.setBackground(new java.awt.Color(120, 120, 120));
        btnE7.setToolTipText("");
        btnE7.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.add(btnE7);

        btnF7.setBackground(new java.awt.Color(204, 255, 204));
        btnF7.setToolTipText("");
        btnF7.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.add(btnF7);

        btnG7.setBackground(new java.awt.Color(120, 120, 120));
        btnG7.setToolTipText("");
        btnG7.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.add(btnG7);

        btnH7.setBackground(new java.awt.Color(204, 255, 204));
        btnH7.setToolTipText("");
        btnH7.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.add(btnH7);

        btnA6.setBackground(new java.awt.Color(204, 255, 204));
        btnA6.setToolTipText("");
        btnA6.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.add(btnA6);

        btnB6.setBackground(new java.awt.Color(120, 120, 120));
        btnB6.setToolTipText("");
        btnB6.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.add(btnB6);

        btnC6.setBackground(new java.awt.Color(204, 255, 204));
        btnC6.setToolTipText("");
        btnC6.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.add(btnC6);

        btnD6.setBackground(new java.awt.Color(120, 120, 120));
        btnD6.setToolTipText("");
        btnD6.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.add(btnD6);

        btnE6.setBackground(new java.awt.Color(204, 255, 204));
        btnE6.setToolTipText("");
        btnE6.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.add(btnE6);

        btnF6.setBackground(new java.awt.Color(120, 120, 120));
        btnF6.setToolTipText("");
        btnF6.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.add(btnF6);

        btnG6.setBackground(new java.awt.Color(204, 255, 204));
        btnG6.setToolTipText("");
        btnG6.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.add(btnG6);

        btnH6.setBackground(new java.awt.Color(120, 120, 120));
        btnH6.setToolTipText("");
        btnH6.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.add(btnH6);

        btnA5.setBackground(new java.awt.Color(120, 120, 120));
        btnA5.setToolTipText("");
        btnA5.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.add(btnA5);

        btnB5.setBackground(new java.awt.Color(204, 255, 204));
        btnB5.setToolTipText("");
        btnB5.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.add(btnB5);

        btnC5.setBackground(new java.awt.Color(120, 120, 120));
        btnC5.setToolTipText("");
        btnC5.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.add(btnC5);

        btnD5.setBackground(new java.awt.Color(204, 255, 204));
        btnD5.setToolTipText("");
        btnD5.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.add(btnD5);

        btnE5.setBackground(new java.awt.Color(120, 120, 120));
        btnE5.setToolTipText("");
        btnE5.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.add(btnE5);

        btnF5.setBackground(new java.awt.Color(204, 255, 204));
        btnF5.setToolTipText("");
        btnF5.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.add(btnF5);

        btnG5.setBackground(new java.awt.Color(120, 120, 120));
        btnG5.setToolTipText("");
        btnG5.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.add(btnG5);

        btnH5.setBackground(new java.awt.Color(204, 255, 204));
        btnH5.setToolTipText("");
        btnH5.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.add(btnH5);

        btnA4.setBackground(new java.awt.Color(204, 255, 204));
        btnA4.setToolTipText("");
        btnA4.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.add(btnA4);

        btnB4.setBackground(new java.awt.Color(120, 120, 120));
        btnB4.setToolTipText("");
        btnB4.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.add(btnB4);

        btnC4.setBackground(new java.awt.Color(204, 255, 204));
        btnC4.setToolTipText("");
        btnC4.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.add(btnC4);

        btnD4.setBackground(new java.awt.Color(120, 120, 120));
        btnD4.setToolTipText("");
        btnD4.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.add(btnD4);

        btnE4.setBackground(new java.awt.Color(204, 255, 204));
        btnE4.setToolTipText("");
        btnE4.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.add(btnE4);

        btnF4.setBackground(new java.awt.Color(120, 120, 120));
        btnF4.setToolTipText("");
        btnF4.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.add(btnF4);

        btnG4.setBackground(new java.awt.Color(204, 255, 204));
        btnG4.setToolTipText("");
        btnG4.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.add(btnG4);

        btnH4.setBackground(new java.awt.Color(120, 120, 120));
        btnH4.setToolTipText("");
        btnH4.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.add(btnH4);

        btnA3.setBackground(new java.awt.Color(120, 120, 120));
        btnA3.setToolTipText("");
        btnA3.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.add(btnA3);

        btnB3.setBackground(new java.awt.Color(204, 255, 204));
        btnB3.setToolTipText("");
        btnB3.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.add(btnB3);

        btnC3.setBackground(new java.awt.Color(120, 120, 120));
        btnC3.setToolTipText("");
        btnC3.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.add(btnC3);

        btnD3.setBackground(new java.awt.Color(204, 255, 204));
        btnD3.setToolTipText("");
        btnD3.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.add(btnD3);

        btnE3.setBackground(new java.awt.Color(120, 120, 120));
        btnE3.setToolTipText("");
        btnE3.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.add(btnE3);

        btnF3.setBackground(new java.awt.Color(204, 255, 204));
        btnF3.setToolTipText("");
        btnF3.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.add(btnF3);

        btnG3.setBackground(new java.awt.Color(120, 120, 120));
        btnG3.setToolTipText("");
        btnG3.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.add(btnG3);

        btnH3.setBackground(new java.awt.Color(204, 255, 204));
        btnH3.setToolTipText("");
        btnH3.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.add(btnH3);

        btnA2.setBackground(new java.awt.Color(204, 255, 204));
        btnA2.setToolTipText("");
        btnA2.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.add(btnA2);

        btnB2.setBackground(new java.awt.Color(120, 120, 120));
        btnB2.setToolTipText("");
        btnB2.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.add(btnB2);

        btnC2.setBackground(new java.awt.Color(204, 255, 204));
        btnC2.setToolTipText("");
        btnC2.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.add(btnC2);

        btnD2.setBackground(new java.awt.Color(120, 120, 120));
        btnD2.setToolTipText("");
        btnD2.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.add(btnD2);

        btnE2.setBackground(new java.awt.Color(204, 255, 204));
        btnE2.setToolTipText("");
        btnE2.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.add(btnE2);

        btnF2.setBackground(new java.awt.Color(120, 120, 120));
        btnF2.setToolTipText("");
        btnF2.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.add(btnF2);

        btnG2.setBackground(new java.awt.Color(204, 255, 204));
        btnG2.setToolTipText("");
        btnG2.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.add(btnG2);

        btnH2.setBackground(new java.awt.Color(120, 120, 120));
        btnH2.setToolTipText("");
        btnH2.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.add(btnH2);

        btnA1.setBackground(new java.awt.Color(120, 120, 120));
        btnA1.setToolTipText("");
        btnA1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.add(btnA1);

        btnB1.setBackground(new java.awt.Color(204, 255, 204));
        btnB1.setToolTipText("");
        btnB1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.add(btnB1);

        btnC1.setBackground(new java.awt.Color(120, 120, 120));
        btnC1.setToolTipText("");
        btnC1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.add(btnC1);

        btnD1.setBackground(new java.awt.Color(204, 255, 204));
        btnD1.setToolTipText("");
        btnD1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.add(btnD1);

        btnE1.setBackground(new java.awt.Color(120, 120, 120));
        btnE1.setToolTipText("");
        btnE1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.add(btnE1);

        btnF1.setBackground(new java.awt.Color(204, 255, 204));
        btnF1.setToolTipText("");
        btnF1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.add(btnF1);

        btnG1.setBackground(new java.awt.Color(120, 120, 120));
        btnG1.setToolTipText("");
        btnG1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.add(btnG1);

        btnH1.setBackground(new java.awt.Color(204, 255, 204));
        btnH1.setToolTipText("");
        btnH1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.add(btnH1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 643, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 563, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BoardJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BoardJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JButton btnA1;
    public static javax.swing.JButton btnA2;
    public static javax.swing.JButton btnA3;
    public static javax.swing.JButton btnA4;
    public static javax.swing.JButton btnA5;
    public static javax.swing.JButton btnA6;
    public static javax.swing.JButton btnA7;
    public static javax.swing.JButton btnA8;
    public static javax.swing.JButton btnB1;
    public static javax.swing.JButton btnB2;
    public static javax.swing.JButton btnB3;
    public static javax.swing.JButton btnB4;
    public static javax.swing.JButton btnB5;
    public static javax.swing.JButton btnB6;
    public static javax.swing.JButton btnB7;
    public static javax.swing.JButton btnB8;
    public static javax.swing.JButton btnC1;
    public static javax.swing.JButton btnC2;
    public static javax.swing.JButton btnC3;
    public static javax.swing.JButton btnC4;
    public static javax.swing.JButton btnC5;
    public static javax.swing.JButton btnC6;
    public static javax.swing.JButton btnC7;
    public static javax.swing.JButton btnC8;
    public static javax.swing.JButton btnD1;
    public static javax.swing.JButton btnD2;
    public static javax.swing.JButton btnD3;
    public static javax.swing.JButton btnD4;
    public static javax.swing.JButton btnD5;
    public static javax.swing.JButton btnD6;
    public static javax.swing.JButton btnD7;
    public static javax.swing.JButton btnD8;
    public static javax.swing.JButton btnE1;
    public static javax.swing.JButton btnE2;
    public static javax.swing.JButton btnE3;
    public static javax.swing.JButton btnE4;
    public static javax.swing.JButton btnE5;
    public static javax.swing.JButton btnE6;
    public static javax.swing.JButton btnE7;
    public static javax.swing.JButton btnE8;
    public static javax.swing.JButton btnF1;
    public static javax.swing.JButton btnF2;
    public static javax.swing.JButton btnF3;
    public static javax.swing.JButton btnF4;
    public static javax.swing.JButton btnF5;
    public static javax.swing.JButton btnF6;
    public static javax.swing.JButton btnF7;
    public static javax.swing.JButton btnF8;
    public static javax.swing.JButton btnG1;
    public static javax.swing.JButton btnG2;
    public static javax.swing.JButton btnG3;
    public static javax.swing.JButton btnG4;
    public static javax.swing.JButton btnG5;
    public static javax.swing.JButton btnG6;
    public static javax.swing.JButton btnG7;
    public static javax.swing.JButton btnG8;
    public static javax.swing.JButton btnH1;
    public static javax.swing.JButton btnH2;
    public static javax.swing.JButton btnH3;
    public static javax.swing.JButton btnH4;
    public static javax.swing.JButton btnH5;
    public static javax.swing.JButton btnH6;
    public static javax.swing.JButton btnH7;
    public static javax.swing.JButton btnH8;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
