package GUI;

import Client.Client;
import Domain.Request;
import Domain.User;
import java.awt.Component;
import java.awt.event.MouseMotionListener;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.io.IOException;
import javax.swing.JInternalFrame;
import javax.swing.JOptionPane;
import javax.swing.plaf.basic.BasicInternalFrameUI;

/**
 *
 * @author reych
 */
public class MainJFrame extends javax.swing.JFrame {
    
    private User user;
    public static Client clientSocket;
    public static String USERCONTROL;
    
    public MainJFrame() {
        initComponents();
        this.setLocationRelativeTo(null);
        //Cierre
        this.setDefaultCloseOperation(DO_NOTHING_ON_CLOSE);
        this.addWindowListener(new WindowAdapter() {
            @Override
            public void windowClosing(WindowEvent e) {
                String btnCierre[] = {"Close", "Cancel"};
                int eleccion = JOptionPane.showOptionDialog(null, "Do you want to close the application?",
                        "Close program.", 0, 0, null, btnCierre, this);
                if (eleccion == JOptionPane.YES_OPTION) {
                    if (clientSocket != null) {
                        // Envia el mensaje al servidor indicando que el usuario se está desconectando
                        clientSocket.sendRequestToServer(new Request(USERCONTROL, "log out"));
                    }
                    System.exit(0);
                }
            }
        }
        );
    }

    /*
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        label = new javax.swing.JLabel();
        jDesktopPanel = new javax.swing.JDesktopPane();
        gameTittle = new javax.swing.JLabel();
        passwordTittle = new javax.swing.JLabel();
        loggin = new java.awt.Button();
        userTextField = new javax.swing.JTextField();
        jPasswordField1 = new javax.swing.JPasswordField();
        userTittle = new javax.swing.JLabel();
        register = new java.awt.Button();
        alert = new javax.swing.JLabel();

        label.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/initBackground.jpg"))); // NOI18N

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Game");
        setLocation(new java.awt.Point(0, 0));
        setMaximumSize(new java.awt.Dimension(700, 900));
        setPreferredSize(new java.awt.Dimension(700, 900));
        setResizable(false);

        jDesktopPanel.setBackground(new java.awt.Color(255, 255, 255));
        jDesktopPanel.setMaximumSize(new java.awt.Dimension(700, 900));
        jDesktopPanel.setPreferredSize(new java.awt.Dimension(700, 900));

        gameTittle.setFont(new java.awt.Font("Castellar", 1, 18)); // NOI18N
        gameTittle.setForeground(new java.awt.Color(0, 153, 153));
        gameTittle.setText("GAME");
        jDesktopPanel.add(gameTittle);
        gameTittle.setBounds(30, 20, 221, 40);

        passwordTittle.setFont(new java.awt.Font("Castellar", 1, 18)); // NOI18N
        passwordTittle.setText("Password:");
        jDesktopPanel.add(passwordTittle);
        passwordTittle.setBounds(120, 170, 150, 40);

        loggin.setBackground(new java.awt.Color(0, 102, 102));
        loggin.setFont(new java.awt.Font("Cascadia Mono", 0, 12)); // NOI18N
        loggin.setForeground(new java.awt.Color(255, 255, 255));
        loggin.setLabel("Log in");
        loggin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                logInMouseClicked(evt);
            }
        });
        jDesktopPanel.add(loggin);
        loggin.setBounds(290, 220, 190, 30);

        userTextField.setFont(new java.awt.Font("Segoe Print", 0, 16)); // NOI18N
        jDesktopPanel.add(userTextField);
        userTextField.setBounds(290, 120, 190, 30);

        jPasswordField1.setFont(new java.awt.Font("Segoe Print", 0, 16)); // NOI18N
        jDesktopPanel.add(jPasswordField1);
        jPasswordField1.setBounds(290, 170, 190, 30);

        userTittle.setFont(new java.awt.Font("Castellar", 1, 18)); // NOI18N
        userTittle.setText("User:");
        jDesktopPanel.add(userTittle);
        userTittle.setBounds(130, 110, 70, 40);

        register.setBackground(new java.awt.Color(51, 0, 51));
        register.setFont(new java.awt.Font("Cascadia Mono", 0, 12)); // NOI18N
        register.setForeground(new java.awt.Color(255, 255, 255));
        register.setLabel("Create new account");
        register.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                newAccountMouseClicked(evt);
            }
        });
        jDesktopPanel.add(register);
        register.setBounds(290, 270, 190, 30);

        alert.setForeground(new java.awt.Color(255, 255, 255));
        alert.setText(" ");
        jDesktopPanel.add(alert);
        alert.setBounds(290, 70, 190, 22);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jDesktopPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        getAccessibleContext().setAccessibleName("Class Royale.");
        getAccessibleContext().setAccessibleDescription("Game.");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void logInMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logInMouseClicked
        this.loggin.setEnabled(false);        
        
        //Case 1. Verificamos la informacion
        if (!this.jPasswordField1.getText().isEmpty() & !this.userTextField.getText().isEmpty()) {

            user = new User(this.userTextField.getText(), jPasswordField1.getText());
            user.setAction("loggin");
          
            if (clientSocket == null) {
                connectToServer();
            }
            
            // Enviamos el objeto User al servidor a través del socket
            clientSocket.sendUserToServer(user);

            // Obtenemos la respuesta del servidor y la mostramos en la interfaz gráfica
              String message = clientSocket.receiveMessageFromServer();
              this.alert.setText(message);
                            
              //Cargamos el inicio
              if (message.equalsIgnoreCase("init")) {
                  disableComponents();
                  USERCONTROL=user.getUser();
                  InicioJInternalFrame inicio=new InicioJInternalFrame(this, user.getUser());
                  inicio.setVisible(true);
                  this.jDesktopPanel.add(inicio);
                  disableInternalFrameMove(inicio);                                                
              }
           
        } else {
            alert.setText("Incomplete data");
            
        }
                this.loggin.setEnabled(true);
    }//GEN-LAST:event_logInMouseClicked

    //visualizar el JFrameInternal para el registro
    private void newAccountMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_newAccountMouseClicked
        /* Create and display the form */
        disableComponents();
        RegistrationJInternalFrame registration = new RegistrationJInternalFrame(this);
        registration.setVisible(true);
        disableInternalFrameMove(registration);
        this.jDesktopPanel.add(registration);

    }//GEN-LAST:event_newAccountMouseClicked

    private void disableInternalFrameMove(JInternalFrame frame){
     // Deshabilitar el comportamiento de arrastrar y mover para el RegistrationJInternalFrame
        frame.setBorder(null);
        BasicInternalFrameUI ui = (BasicInternalFrameUI) frame.getUI();
        Component northPane = ui.getNorthPane();
        MouseMotionListener[] motionListeners = (MouseMotionListener[]) northPane.getListeners(MouseMotionListener.class);
        for (MouseMotionListener listener : motionListeners) {
            northPane.removeMouseMotionListener(listener);
        }

    }
    
    /*
     * Método para conectarse al servidor.
     * Crea una instancia de Client para establecer la conexión con el servidor.
     * Si ocurre algún error, se mostrará un mensaje en la interfaz gráfica.
     */
    private void connectToServer() {
        try {
            clientSocket = new Client("localhost", 5025);
        } catch (IOException ex) {
            this.alert.setText("Internal error");
        }
    }

    //desabilitar los componentes
    private void disableComponents() {
        // Ocultar los componentes que deseas
        gameTittle.setVisible(false);
        passwordTittle.setVisible(false);
        loggin.setVisible(false);
        userTextField.setVisible(false);
        jPasswordField1.setVisible(false);
        userTittle.setVisible(false);
        register.setVisible(false);
        alert.setVisible(false);
    }

    // Método para mostrar los componentes ocultos
    public void enableComponents() {
        gameTittle.setVisible(true);
        passwordTittle.setVisible(true);
        loggin.setVisible(true);
        userTextField.setText("");
        userTextField.setVisible(true);
        jPasswordField1.setText("");
        jPasswordField1.setVisible(true);
        userTittle.setVisible(true);
        register.setVisible(true);
        alert.setText("");
        alert.setVisible(true);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel alert;
    private javax.swing.JLabel gameTittle;
    private javax.swing.JDesktopPane jDesktopPanel;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JLabel label;
    private java.awt.Button loggin;
    private javax.swing.JLabel passwordTittle;
    private java.awt.Button register;
    private javax.swing.JTextField userTextField;
    private javax.swing.JLabel userTittle;
    // End of variables declaration//GEN-END:variables
}
